// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY3zwTNEfAQJPbajwvF3W5cRW38eEXE5M',
    appId: '1:61528015641:web:f19981253b0e70343dfb88',
    messagingSenderId: '61528015641',
    projectId: 'pure-drop-be0d4',
    authDomain: 'pure-drop-be0d4.firebaseapp.com',
    databaseURL: 'https://pure-drop-be0d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pure-drop-be0d4.firebasestorage.app',
    measurementId: 'G-LSTHZTZ3PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjaMTmxMnd6JSeltBQyeeHEZ4M2HTUXEc',
    appId: '1:61528015641:android:e6d9c69a04d30e953dfb88',
    messagingSenderId: '61528015641',
    projectId: 'pure-drop-be0d4',
    databaseURL: 'https://pure-drop-be0d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pure-drop-be0d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPjlKsRHBOeDsPoF9OT5ke9ej9VOAGofE',
    appId: '1:61528015641:ios:10d677ddc89aa5793dfb88',
    messagingSenderId: '61528015641',
    projectId: 'pure-drop-be0d4',
    databaseURL: 'https://pure-drop-be0d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pure-drop-be0d4.firebasestorage.app',
    androidClientId: '61528015641-5217s2tbebd2eu0vh7p9edpbh11uinf9.apps.googleusercontent.com',
    iosClientId: '61528015641-0q5273lmv455upi789baogs3ukoii7lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pureDrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPjlKsRHBOeDsPoF9OT5ke9ej9VOAGofE',
    appId: '1:61528015641:ios:10d677ddc89aa5793dfb88',
    messagingSenderId: '61528015641',
    projectId: 'pure-drop-be0d4',
    databaseURL: 'https://pure-drop-be0d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pure-drop-be0d4.firebasestorage.app',
    androidClientId: '61528015641-5217s2tbebd2eu0vh7p9edpbh11uinf9.apps.googleusercontent.com',
    iosClientId: '61528015641-0q5273lmv455upi789baogs3ukoii7lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pureDrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY3zwTNEfAQJPbajwvF3W5cRW38eEXE5M',
    appId: '1:61528015641:web:b63ab0c8bf90650b3dfb88',
    messagingSenderId: '61528015641',
    projectId: 'pure-drop-be0d4',
    authDomain: 'pure-drop-be0d4.firebaseapp.com',
    databaseURL: 'https://pure-drop-be0d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pure-drop-be0d4.firebasestorage.app',
    measurementId: 'G-9XM3SWEZZ1',
  );
}
